[package]
name = "gelx_example"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
gelx = { workspace = true, features = ["with_all"] }

[lints]
workspace = true

[features]
ssr = ["gelx/query", "gelx/serde", "gelx/strum", "gelx/builder"]

[package.metadata.gelx]
queries = "./queries"
features = { query = "ssr", serde = "ssr", strum = "ssr", builder = "ssr" }
