[alias]
# bins
deny = ["bin", "cargo-deny"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]

# testing
test_all_features = ["nextest", "run", "--features", "builder,query,serde,strum"]
test_no_features = ["nextest", "run"]
test_docs = ["test", "--doc", "--features", "builder,query,serde,strum"]
coverage_all_features = ["llvm-cov", "--no-report", "--features", "builder,query,serde,strum"]
coverage_no_features = ["llvm-cov", "--no-report"]
coverage_docs = ["llvm-cov", "--no-report", "--doc", "--features", "builder,query,serde,strum"]
coverage_report = ["llvm-cov", "report", "--doctests", "--codecov", "--output-path", "codecov.json"]
